### ISSUE TITLE
The last letter of the alphabet is not used

### ISSUE THREAD

**Issue by auwtch** [viascom/nanoid-postgres#1]
```sql
select nanoid(2, 'ab') from generate_series(1, 10);
-- output:
-- aa
-- aa
-- aa
-- aa
-- aa
-- aa
-- aa
-- aa
-- aa
```

I think a problem is here https://github.com/viascom/nanoid-postgres/blob/840be7c3c86e32032eee7e3cf4563ac35bf269e0/nanoid.sql#L45
Since postgres starts indexing from 1 and not 0 maybe it should be `alphabetIndex + 1`?

**Comment by nik-sta** [comment]
Hi @blasterpistol. Thanks for creating an issue and letting us know. We have analysed it, and based on your report, we have developed a fix. Cheers, Nikola
