### ISSUE TITLE
Usage of leakproof in function definition prevents usage

### ISSUE THREAD

**Issue by theo-m** [viascom/nanoid-postgres#11]
Hey, thanks for the lib, would love to use it.
Small area of uncertainty for me though is the use of this `LEAKPROOF` attribute in the function definition:

https://github.com/viascom/nanoid-postgres/blob/70cdeae6b6b31c37039767d3dc9ce40d90fc4b81/nanoid.sql#L38

This attribute is allowed only to superuser in certain contexts (I've found [this issue](https://github.com/supabase/cli/issues/1011) for supabase, and I'm myself using neon.tech). 

My understanding [from the docs](https://www.postgresql.org/docs/current/sql-createfunction.html#:~:text=Section%C2%A038.7.-,LEAKPROOF,-LEAKPROOF%20indicates%20that) is that this attribute is perhaps not strictly speaking necessary to the function?

I've run the function _without_ the attribute on a migration involving 20k rows, and it's gone well.

**Comment by nik-sta** [comment]
Hi @theo-m 

First off, thank you for considering our library for your project! I'm glad to hear about your interest and appreciate you reaching out with your concerns about the `LEAKPROOF` attribute in the nanoid function. Let's clarify what `LEAKPROOF` means for this function, along with its pros and cons, to help explain its role and reassure you of the safety of modifying it for your setup.

### Why It's Currently Marked as LEAKPROOF
The nanoid function is designed to generate compact, URL-friendly unique identifiers without leaking any information about its operational context or input parameters. By marking it as `LEAKPROOF`, we're essentially ensuring that:

- It doesn't reveal any information about its internal processing through side effects or error messages, adhering to strict security practices.
- It can be safely utilised in environments with row-level security (RLS) and security barrier views, allowing for specific optimisations in query execution without compromising data privacy.

### Cons of LEAKPROOF

- Restricted Usage: Only superusers can set or modify this attribute, which might limit flexibility in some managed environments like Supabase, Neon, Cloud (GCP, AWS, Azure)

### Is It Safe to Remove?
Given your use case and the nature of the nanoid function (generating unique identifiers without relying on or revealing external data), removing the `LEAKPROOF` attribute should not introduce any security risks or functional issues. If you've already run tests migrating 20k rows without problems, the function performs as expected outside the strict `LEAKPROOF` constraints. Removing `LEAKPROOF` could indeed make the function more accessible in environments where setting this attribute is restricted to superusers.

In summary, while `LEAKPROOF` offers specific benefits in tightly controlled environments, the nature of the nanoid function makes it safe to remove this attribute, significantly if it simplifies deployment and usage in your specific context. Feel free to adjust the attribute to fit your infrastructure and security requirements.

We're considering removing `LEAKPROOF` as the default setting and advising users to set it using row-level security (RLS) and security barrier views. This decision will be made after an analysis in the coming days.

Based on our own experience, we can confirm that the function runs well and efficiently on our GCP instance without the `LEAKPROOF` setting.

I hope this clarifies any uncertainties. Please don't hesitate to contact me if you have any questions or need further assistance.

Cheers, Nikola

**Comment by nik-sta** [comment]
This question or issue is being closed due to inactivity, but we appreciate your contribution. If the question or problem persists or you have more to add, please reopen it or start a new issue and link back to this one. Your input is valuable, and we’re here to engage. Thanks for your understanding! Cheers!
