### ISSUE TITLE
Should this be marked as volatile instead of stable

### ISSUE THREAD

**Issue by hixus** [viascom/nanoid-postgres#3]
Should this be marked as volatile instead of stable? Noticed pr for similar issue in another [implementation](https://github.com/Jakeii/nanoid-postgres/pull/3).

According to [docs](https://www.postgresql.org/docs/current/xfunc-volatility.html) "Even a function with no side-effects needs to be labeled VOLATILE if its value can change within a single query; some examples are random(), currval(), timeofday()"

**Comment by nik-sta** [comment]
Hi @hixus  :) absolutely! Thanks for taking the time and opening an issue. I will change it asap.

**Comment by nik-sta** [comment]
I changed and tested it, and it's now on the main branch available.
